"""Vendored hub-address exclusion set (M6).

CEX hot wallets, bridges, mixers, fiat ramps, 4337 bundlers/paymasters —
entities that first-fund many UNRELATED users. The Sybil filter must not
cluster reviewers through them, or everyone who onboarded via the same
exchange collapses into one false Sybil ring (Research4-M6-sybil.md §3).

Data: src/preflight402/reputation/data/hub_addresses.txt.gz, generated by
scripts/build_hub_labels.py from eth-labels (MIT). Addresses are EOAs whose
keys work on every EVM chain, so one flat set serves all chains. Coverage
inherits Etherscan-label gaps — the cross-agent fan-out heuristic in
sybil.py is the belt-and-braces for unlabeled hubs.
"""

from __future__ import annotations

import gzip
from functools import cache
from importlib import resources


@cache
def hub_addresses() -> frozenset[str]:
    """The lowercased hub address set, loaded once per process (~37k entries)."""
    data = resources.files("preflight402.reputation").joinpath("data/hub_addresses.txt.gz")
    with data.open("rb") as raw, gzip.open(raw, "rt", encoding="utf-8") as fh:
        return frozenset(
            line.strip().lower() for line in fh if line.strip() and not line.startswith("#")
        )


def is_hub(address: str) -> bool:
    """True when `address` is a labeled funding hub (case-insensitive)."""
    return address.lower() in hub_addresses()
